// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "app/frontend/biz/router/auth"
	cart "app/frontend/biz/router/cart"
	category "app/frontend/biz/router/category"
	checkout "app/frontend/biz/router/checkout"
	home "app/frontend/biz/router/home"
	order "app/frontend/biz/router/order"
	product "app/frontend/biz/router/product"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	product.Register(r)

	order.Register(r)

	checkout.Register(r)

	category.Register(r)

	cart.Register(r)

	auth.Register(r)

	home.Register(r)
}
